/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

import java.awt.Color;
import static java.lang.Math.cbrt;
import javax.swing.JOptionPane;

/**
 *
 * @author Edineuza
 */
public class FrmCubicRoot extends javax.swing.JFrame {

    /**
     * Creates new form FrmCubicRoot
     */
    public FrmCubicRoot() {
        initComponents();
        
        btnClose.setBackground(new Color(0, 102, 204));
        btnMinimize.setBackground(new Color(0, 102, 204));
        btnEquals.setBackground(new Color(0, 102, 204));
        btnReset.setBackground(new Color(0, 102, 204));
        btnMinus.setBackground(new Color(0, 102, 204));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBack = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        txtValue1 = new javax.swing.JTextField();
        txtResult = new javax.swing.JTextField();
        lblVal1 = new javax.swing.JLabel();
        btnEquals = new javax.swing.JButton();
        lblTop = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        lblMin = new javax.swing.JLabel();
        lblVal = new javax.swing.JLabel();
        lblExpo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panBack.setBackground(new java.awt.Color(30, 30, 30));

        btnClose.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("x");
        btnClose.setBorder(null);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusable(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnMinimize.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setText("-");
        btnMinimize.setBorder(null);
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.setFocusable(false);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        txtValue1.setBackground(new java.awt.Color(70, 70, 70));
        txtValue1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtValue1.setForeground(new java.awt.Color(255, 255, 255));
        txtValue1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValue1KeyReleased(evt);
            }
        });

        txtResult.setEditable(false);
        txtResult.setBackground(new java.awt.Color(70, 70, 70));
        txtResult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtResult.setForeground(new java.awt.Color(255, 255, 255));

        lblVal1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVal1.setForeground(new java.awt.Color(255, 255, 255));
        lblVal1.setText("Value :");

        btnEquals.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEquals.setForeground(new java.awt.Color(255, 255, 255));
        btnEquals.setText("=");
        btnEquals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });

        lblTop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTop.setForeground(new java.awt.Color(255, 255, 255));
        lblTop.setText("CUBIC ROOT");

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("CE");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnMinus.setForeground(new java.awt.Color(255, 255, 255));
        btnMinus.setText("-");
        btnMinus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        lblMin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMin.setForeground(new java.awt.Color(255, 255, 255));
        lblMin.setText("Negative");

        lblVal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblVal.setForeground(new java.awt.Color(255, 255, 255));
        lblVal.setText("x");

        lblExpo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblExpo.setForeground(new java.awt.Color(255, 255, 255));
        lblExpo.setText("1/3");

        javax.swing.GroupLayout panBackLayout = new javax.swing.GroupLayout(panBack);
        panBack.setLayout(panBackLayout);
        panBackLayout.setHorizontalGroup(
            panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBackLayout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBackLayout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBackLayout.createSequentialGroup()
                        .addComponent(btnEquals)
                        .addGap(126, 126, 126)
                        .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBackLayout.createSequentialGroup()
                        .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panBackLayout.createSequentialGroup()
                                .addComponent(lblVal1)
                                .addGap(26, 26, 26)
                                .addComponent(txtValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(panBackLayout.createSequentialGroup()
                                .addComponent(lblVal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblExpo)
                                .addGap(61, 61, 61)))
                        .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMin))
                        .addGap(63, 63, 63))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTop)
                .addGap(149, 149, 149))
        );
        panBackLayout.setVerticalGroup(
            panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBackLayout.createSequentialGroup()
                .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnMinimize))
                .addGap(16, 16, 16)
                .addComponent(lblTop)
                .addGap(53, 53, 53)
                .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMinus))
                    .addGroup(panBackLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblVal1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBackLayout.createSequentialGroup()
                        .addComponent(lblMin)
                        .addGap(18, 18, 18)
                        .addComponent(btnEquals)
                        .addGap(11, 11, 11)
                        .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset)))
                    .addComponent(lblVal)
                    .addComponent(lblExpo))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
        new FrmHome().setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void txtValue1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValue1KeyReleased
        try {
            int x = Integer.parseInt(txtValue1.getText());
        } catch (NumberFormatException ex) {
            txtValue1.setText("");
        }
    }//GEN-LAST:event_txtValue1KeyReleased

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        //If textbox is empty
        if(txtValue1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty fields not allowed!");
        }
        else {
            int x;
            x = Integer.parseInt(txtValue1.getText());
            double root = cbrt(x);
            String f = Double.toString(root);
            if(f.length() > 8)
            txtResult.setText(f.substring(0,7));
            else
            txtResult.setText(f);
            
            btnMinus.setEnabled(false);
            txtValue1.setEditable(false);
        }
    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtValue1.setText("");

        txtResult.setText("");
        txtValue1.setEditable(true);
        btnMinus.setEnabled(true);
        txtValue1.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        if(txtValue1.getText().equals("")) {
            txtValue1.requestFocus();
        }
        else {
            txtValue1.setText("-" + txtValue1.getText());
            btnMinus.setEnabled(false);
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCubicRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCubicRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCubicRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCubicRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCubicRoot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblExpo;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblTop;
    private javax.swing.JLabel lblVal;
    private javax.swing.JLabel lblVal1;
    private javax.swing.JPanel panBack;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtValue1;
    // End of variables declaration//GEN-END:variables
}
