/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Edineuza
 */
public class FrmDiv extends javax.swing.JFrame {

    /**
     * Creates new form FrmDiv
     */
    public FrmDiv() {
        initComponents();
        
        btnClose.setBackground(new Color(0, 102, 204));
        btnMinimize.setBackground(new Color(0, 102, 204));
        btnEquals.setBackground(new Color(0, 102, 204));
        btnReset.setBackground(new Color(0, 102, 204));
        btnMinus.setBackground(new Color(0, 102, 204));
        btnMinus2.setBackground(new Color(0, 102, 204));
        
        txtValue1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBack = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        txtValue1 = new javax.swing.JTextField();
        txtValue2 = new javax.swing.JTextField();
        txtResult = new javax.swing.JTextField();
        lblDiv = new javax.swing.JLabel();
        btnEquals = new javax.swing.JButton();
        lblVal1 = new javax.swing.JLabel();
        lblVal2 = new javax.swing.JLabel();
        lblTop = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        lblMin1 = new javax.swing.JLabel();
        btnMinus2 = new javax.swing.JButton();
        lblMin2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panBack.setBackground(new java.awt.Color(30, 30, 30));

        btnClose.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("x");
        btnClose.setBorder(null);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusable(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnMinimize.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setText("-");
        btnMinimize.setBorder(null);
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.setFocusable(false);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        txtValue1.setBackground(new java.awt.Color(70, 70, 70));
        txtValue1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtValue1.setForeground(new java.awt.Color(255, 255, 255));
        txtValue1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValue1KeyReleased(evt);
            }
        });

        txtValue2.setBackground(new java.awt.Color(70, 70, 70));
        txtValue2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtValue2.setForeground(new java.awt.Color(255, 255, 255));
        txtValue2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValue2KeyReleased(evt);
            }
        });

        txtResult.setEditable(false);
        txtResult.setBackground(new java.awt.Color(70, 70, 70));
        txtResult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtResult.setForeground(new java.awt.Color(255, 255, 255));

        lblDiv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDiv.setForeground(new java.awt.Color(255, 255, 255));
        lblDiv.setText(" /");

        btnEquals.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEquals.setForeground(new java.awt.Color(255, 255, 255));
        btnEquals.setText("=");
        btnEquals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });

        lblVal1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVal1.setForeground(new java.awt.Color(255, 255, 255));
        lblVal1.setText("Value 1:");

        lblVal2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVal2.setForeground(new java.awt.Color(255, 255, 255));
        lblVal2.setText("Value 2:");

        lblTop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTop.setForeground(new java.awt.Color(255, 255, 255));
        lblTop.setText("DIVISION");

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("CE");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnMinus.setForeground(new java.awt.Color(255, 255, 255));
        btnMinus.setText("-");
        btnMinus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        lblMin1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMin1.setForeground(new java.awt.Color(255, 255, 255));
        lblMin1.setText("Negative");

        btnMinus2.setForeground(new java.awt.Color(255, 255, 255));
        btnMinus2.setText("-");
        btnMinus2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinus2ActionPerformed(evt);
            }
        });

        lblMin2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMin2.setForeground(new java.awt.Color(255, 255, 255));
        lblMin2.setText("Negative");

        javax.swing.GroupLayout panBackLayout = new javax.swing.GroupLayout(panBack);
        panBack.setLayout(panBackLayout);
        panBackLayout.setHorizontalGroup(
            panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBackLayout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBackLayout.createSequentialGroup()
                        .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBackLayout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
            .addGroup(panBackLayout.createSequentialGroup()
                .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBackLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(lblTop))
                    .addGroup(panBackLayout.createSequentialGroup()
                        .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panBackLayout.createSequentialGroup()
                                    .addGap(179, 179, 179)
                                    .addComponent(btnEquals))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBackLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblVal2)
                                        .addComponent(lblVal1))
                                    .addGap(26, 26, 26)
                                    .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtValue1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panBackLayout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(lblDiv)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinus2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMin1)
                            .addComponent(lblMin2))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panBackLayout.setVerticalGroup(
            panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBackLayout.createSequentialGroup()
                .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnMinimize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTop)
                .addGap(18, 18, 18)
                .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBackLayout.createSequentialGroup()
                        .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panBackLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblVal1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDiv)
                        .addGap(13, 13, 13)
                        .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVal2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEquals)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBackLayout.createSequentialGroup()
                        .addComponent(btnMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMin1)
                        .addGap(55, 55, 55)
                        .addComponent(btnMinus2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMin2)
                        .addGap(27, 27, 27)))
                .addGroup(panBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
        new FrmHome().setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtValue1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValue1KeyReleased
        try {
            int x = Integer.parseInt(txtValue1.getText());
        } catch (NumberFormatException ex) {
            txtValue1.setText("");
        }
    }//GEN-LAST:event_txtValue1KeyReleased

    private void txtValue2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValue2KeyReleased
        try {
            int x = Integer.parseInt(txtValue2.getText());
        } catch (NumberFormatException ex) {
            txtValue2.setText("");
        }
    }//GEN-LAST:event_txtValue2KeyReleased

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        //If textbox is empty
        if(txtValue1.getText().equals("") || txtValue2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty fields not allowed!");
        }
        else {
            double x, y, div;
            x = Double.parseDouble(txtValue1.getText());
            y = Double.parseDouble(txtValue2.getText());
            div = x / y;
            //Format decimal part
            String f = Double.toString(div);
            if(f.length() > 6 )
                txtResult.setText(f.substring(0, 7));
            else
                txtResult.setText(f);

            txtValue1.setEditable(false);
            txtValue2.setEditable(false);
            btnMinus.setEnabled(false);
            btnMinus2.setEnabled(false);
        }
    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtValue1.setText("");
        txtValue2.setText("");
        txtResult.setText("");
        txtValue1.setEditable(true);
        txtValue2.setEditable(true);
        btnMinus.setEnabled(true);
        btnMinus2.setEnabled(true);
        txtValue1.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        if(txtValue1.getText().equals("")) {
            txtValue1.requestFocus();
        }
        else {
            txtValue1.setText("-" + txtValue1.getText());
            btnMinus.setEnabled(false);
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMinus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinus2ActionPerformed
        if(txtValue2.getText().equals("")) {
            txtValue2.requestFocus();
        }
        else {
            txtValue2.setText("-" + txtValue2.getText());
            btnMinus2.setEnabled(false);
        }
    }//GEN-LAST:event_btnMinus2ActionPerformed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDiv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDiv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMinus2;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblDiv;
    private javax.swing.JLabel lblMin1;
    private javax.swing.JLabel lblMin2;
    private javax.swing.JLabel lblTop;
    private javax.swing.JLabel lblVal1;
    private javax.swing.JLabel lblVal2;
    private javax.swing.JPanel panBack;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtValue1;
    private javax.swing.JTextField txtValue2;
    // End of variables declaration//GEN-END:variables
}
