/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

import java.awt.Color;
import static java.lang.Math.sqrt;
import javax.swing.JOptionPane;

/**
 *
 * @author Edineuza
 */
public class FrmSecondDegree extends javax.swing.JFrame {

    /**
     * Creates new form FrmSecondDegree
     */
    public FrmSecondDegree() {
        initComponents();
        
        txtValue1.requestFocus();
        btnMinimize.setBackground(new Color(0, 102, 204));
        btnClose2.setBackground(new Color(0, 102, 204));
        btnRoot.setBackground(new Color(0, 102, 204));
        btnReset.setBackground(new Color(0, 102, 204));
        btnMinus.setBackground(new Color(0, 102, 204));
        btnMinus2.setBackground(new Color(0, 102, 204));
        btnMinus3.setBackground(new Color(0, 102, 204));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBack2 = new javax.swing.JPanel();
        btnClose2 = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        txtValue1 = new javax.swing.JTextField();
        txtValue2 = new javax.swing.JTextField();
        txtRoot = new javax.swing.JTextField();
        btnRoot = new javax.swing.JButton();
        lblTop = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        lblMin = new javax.swing.JLabel();
        lblMin2 = new javax.swing.JLabel();
        lblMin3 = new javax.swing.JLabel();
        lblEquation = new javax.swing.JLabel();
        lblEquals = new javax.swing.JLabel();
        btnMinus = new javax.swing.JButton();
        btnMinus2 = new javax.swing.JButton();
        btnMinus3 = new javax.swing.JButton();
        txtValue3 = new javax.swing.JTextField();
        lblRoot = new javax.swing.JLabel();
        lblEquation1 = new javax.swing.JLabel();
        lblEquation2 = new javax.swing.JLabel();
        lblRoot1 = new javax.swing.JLabel();
        txtRoot2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panBack2.setBackground(new java.awt.Color(30, 30, 30));

        btnClose2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnClose2.setForeground(new java.awt.Color(255, 255, 255));
        btnClose2.setText("x");
        btnClose2.setBorder(null);
        btnClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose2.setFocusable(false);
        btnClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose2ActionPerformed(evt);
            }
        });

        btnMinimize.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setText("-");
        btnMinimize.setBorder(null);
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.setFocusable(false);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        txtValue1.setBackground(new java.awt.Color(70, 70, 70));
        txtValue1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtValue1.setForeground(new java.awt.Color(255, 255, 255));
        txtValue1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValue1KeyReleased(evt);
            }
        });

        txtValue2.setBackground(new java.awt.Color(70, 70, 70));
        txtValue2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtValue2.setForeground(new java.awt.Color(255, 255, 255));
        txtValue2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValue2KeyReleased(evt);
            }
        });

        txtRoot.setEditable(false);
        txtRoot.setBackground(new java.awt.Color(70, 70, 70));
        txtRoot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtRoot.setForeground(new java.awt.Color(255, 255, 255));

        btnRoot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRoot.setForeground(new java.awt.Color(255, 255, 255));
        btnRoot.setText("Root");
        btnRoot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRootActionPerformed(evt);
            }
        });

        lblTop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTop.setForeground(new java.awt.Color(255, 255, 255));
        lblTop.setText("SECOND DEGREE EQUATION");

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("CE");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblMin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMin.setForeground(new java.awt.Color(255, 255, 255));
        lblMin.setText("Negative");

        lblMin2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMin2.setForeground(new java.awt.Color(255, 255, 255));
        lblMin2.setText("Negative");

        lblMin3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMin3.setForeground(new java.awt.Color(255, 255, 255));
        lblMin3.setText("Negative");

        lblEquation.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEquation.setForeground(new java.awt.Color(255, 255, 255));
        lblEquation.setText("x +   ");

        lblEquals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEquals.setForeground(new java.awt.Color(255, 255, 255));
        lblEquals.setText("= 0");

        btnMinus.setForeground(new java.awt.Color(255, 255, 255));
        btnMinus.setText("-");
        btnMinus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnMinus2.setForeground(new java.awt.Color(255, 255, 255));
        btnMinus2.setText("-");
        btnMinus2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinus2ActionPerformed(evt);
            }
        });

        btnMinus3.setForeground(new java.awt.Color(255, 255, 255));
        btnMinus3.setText("-");
        btnMinus3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinus3ActionPerformed(evt);
            }
        });

        txtValue3.setBackground(new java.awt.Color(70, 70, 70));
        txtValue3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtValue3.setForeground(new java.awt.Color(255, 255, 255));
        txtValue3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValue3KeyReleased(evt);
            }
        });

        lblRoot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRoot.setForeground(new java.awt.Color(255, 255, 255));
        lblRoot.setText("x' =");

        lblEquation1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEquation1.setForeground(new java.awt.Color(255, 255, 255));
        lblEquation1.setText("2");

        lblEquation2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEquation2.setForeground(new java.awt.Color(255, 255, 255));
        lblEquation2.setText("x +   ");

        lblRoot1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRoot1.setForeground(new java.awt.Color(255, 255, 255));
        lblRoot1.setText("x'' =");

        txtRoot2.setEditable(false);
        txtRoot2.setBackground(new java.awt.Color(70, 70, 70));
        txtRoot2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtRoot2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panBack2Layout = new javax.swing.GroupLayout(panBack2);
        panBack2.setLayout(panBack2Layout);
        panBack2Layout.setHorizontalGroup(
            panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBack2Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblRoot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRoot1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRoot2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBack2Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBack2Layout.createSequentialGroup()
                        .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBack2Layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(34, 34, 34)
                        .addComponent(btnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBack2Layout.createSequentialGroup()
                        .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panBack2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panBack2Layout.createSequentialGroup()
                                        .addComponent(lblMin)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEquation1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panBack2Layout.createSequentialGroup()
                                .addComponent(txtValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEquation)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMinus2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMin2)
                            .addGroup(panBack2Layout.createSequentialGroup()
                                .addComponent(txtValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEquation2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMinus3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMin3)
                            .addGroup(panBack2Layout.createSequentialGroup()
                                .addComponent(txtValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEquals)))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBack2Layout.createSequentialGroup()
                        .addComponent(lblTop)
                        .addGap(195, 195, 195))))
        );
        panBack2Layout.setVerticalGroup(
            panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBack2Layout.createSequentialGroup()
                .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose2)
                    .addComponent(btnMinimize))
                .addGap(9, 9, 9)
                .addComponent(lblTop)
                .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBack2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnMinus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMin)
                            .addComponent(lblEquation1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEquation)))
                    .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panBack2Layout.createSequentialGroup()
                            .addComponent(btnMinus3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblMin3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEquals)))
                        .addGroup(panBack2Layout.createSequentialGroup()
                            .addComponent(btnMinus2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblMin2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEquation2)))))
                .addGap(25, 25, 25)
                .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRoot)
                    .addComponent(btnReset))
                .addGap(18, 18, 18)
                .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRoot2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRoot1))
                    .addGroup(panBack2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRoot)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panBack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panBack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void txtValue1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValue1KeyReleased
        try {
            int x = Integer.parseInt(txtValue1.getText());
            if(txtValue1.getText().length() > 3) {
                JOptionPane.showMessageDialog(null, "Max range reached!");
                txtValue1.setText(txtValue1.getText().substring(0,3));
            }
        } catch (NumberFormatException ex) {
            txtValue1.setText("");
        }
    }//GEN-LAST:event_txtValue1KeyReleased

    private void txtValue2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValue2KeyReleased
        try {
            int x = Integer.parseInt(txtValue2.getText());
            if(txtValue2.getText().length() > 3) {
                JOptionPane.showMessageDialog(null, "Max range reached!");
                txtValue2.setText(txtValue2.getText().substring(0,3));
            }
        } catch (NumberFormatException ex) {
            txtValue2.setText("");
        }
    }//GEN-LAST:event_txtValue2KeyReleased

    private void btnRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRootActionPerformed
        //If textbox is empty
        if(txtValue1.getText().equals("") || txtValue2.getText().equals("") 
            || txtValue3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty fields not allowed!");  
        }
        else {
            double a, b, c, delta, deltaRoot, root1, root2;
            a = Double.parseDouble(txtValue1.getText());
            b = Double.parseDouble(txtValue2.getText());
            c = Double.parseDouble(txtValue3.getText());
            //Mounting equation
            if(a != 0) {
                delta = (b * b) - (4 * a * c);
                deltaRoot = sqrt(delta);
                //positive delta root
                if(deltaRoot >= 0) {
                    root1 = (-b + deltaRoot) / (2 * a);
                    root2 = (-b - deltaRoot) / (2 * a);
                    String f1 = Double.toString(root1);
                    String f2 = Double.toString(root2);
                    
                    txtRoot.setText(f1);
                    txtRoot2.setText(f2);
                }
                 //negative delta root
                else {
                    delta = - delta;
                    deltaRoot = sqrt(delta);
                    txtRoot.setText(Double.toString((-b / 2 * a)).substring(0,2)
                    + " + i" + Double.toString(deltaRoot / 2 * a).substring(0,2));
                    txtRoot2.setText(Double.toString((-b / 2 * a)).substring(0,2)
                    + " - i" + Double.toString(deltaRoot / 2 * a).substring(0,2));
                    //Obs: Rounded values
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Equation isn't quadratic!");
                txtValue1.requestFocus();
            }

            txtValue1.setEditable(false);
            txtValue2.setEditable(false);
            txtValue3.setEditable(false);
            btnMinus.setEnabled(false);
            btnMinus2.setEnabled(false);
            btnMinus3.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_btnRootActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtValue1.setText("");
        txtValue2.setText("");
        txtValue3.setText("");

        txtRoot.setText("");
        txtRoot2.setText("");
        txtValue1.setEditable(true);
        txtValue2.setEditable(true);
        txtValue3.setEditable(true);
        btnMinus.setEnabled(true);
        btnMinus2.setEnabled(true);
        btnMinus3.setEnabled(true);
        txtValue1.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        if(txtValue1.getText().equals("")) {
            txtValue1.requestFocus();
        }
        else {
            txtValue1.setText("-" + txtValue1.getText());
            btnMinus.setEnabled(false);
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMinus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinus2ActionPerformed
        if(txtValue2.getText().equals("")) {
            txtValue2.requestFocus();
        }
        else {
            txtValue2.setText("-" + txtValue2.getText());
            btnMinus2.setEnabled(false);
        }
    }//GEN-LAST:event_btnMinus2ActionPerformed

    private void btnMinus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinus3ActionPerformed
        if(txtValue3.getText().equals("")) {
            txtValue3.requestFocus();
        }
        else {
            txtValue3.setText("-" + txtValue3.getText());
            btnMinus3.setEnabled(false);
        }
    }//GEN-LAST:event_btnMinus3ActionPerformed

    private void txtValue3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValue3KeyReleased
        try {
            int x = Integer.parseInt(txtValue3.getText());
            if(txtValue3.getText().length() > 3) {
                JOptionPane.showMessageDialog(null, "Max range reached!");
                txtValue3.setText(txtValue3.getText().substring(0,3));
            }
        } catch (NumberFormatException ex) {
            txtValue3.setText("");
        }
    }//GEN-LAST:event_txtValue3KeyReleased

    private void btnClose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose2ActionPerformed
        this.dispose();
        new FrmHome().setVisible(true);
    }//GEN-LAST:event_btnClose2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSecondDegree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSecondDegree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSecondDegree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSecondDegree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSecondDegree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose2;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMinus2;
    private javax.swing.JButton btnMinus3;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRoot;
    private javax.swing.JLabel lblEquals;
    private javax.swing.JLabel lblEquation;
    private javax.swing.JLabel lblEquation1;
    private javax.swing.JLabel lblEquation2;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblMin2;
    private javax.swing.JLabel lblMin3;
    private javax.swing.JLabel lblRoot;
    private javax.swing.JLabel lblRoot1;
    private javax.swing.JLabel lblTop;
    private javax.swing.JPanel panBack2;
    private javax.swing.JTextField txtRoot;
    private javax.swing.JTextField txtRoot2;
    private javax.swing.JTextField txtValue1;
    private javax.swing.JTextField txtValue2;
    private javax.swing.JTextField txtValue3;
    // End of variables declaration//GEN-END:variables
}
